---
title: "NASIS Ecosite Assignment Status Report"
version:  "0.1b"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

***

####Configuration
```{r,echo=F,results='asis'}
###
#Enter a regex pattern to match dmudesc
###
dmupattern = "."
cat("DMUID Pattern: ",dmupattern)
##################################

###TODOS
# Currently several independent queries are run to get data from separate tables. 
# It would be more efficient to do the JOINS in SQL rather than in R. I just wasn't sure which tables I'd need so I decided to do all joins on R side.
```

***

```{r, echo=FALSE, results='hide', warning=FALSE, message=FALSE}
library(soilDB)
library(plyr) 
library(knitr)

#modified soilDB function to return lastupdated date and userid
get_component_esd_data_from_NASIS_db2 <- function() {
  # must have RODBC installed
  if(!requireNamespace('RODBC'))
    stop('please install the `RODBC` package', call.=FALSE)
  
  q <- "SELECT coiidref as coiid, ecositeid, ecositenm, 
  ecositeorigin, ecositetype, ecositemlra, ecositelru, ecositenumber, ecositestate, coecosite.recwlupdated, coecosite.recuseriidref
  
  FROM coecosite_View_1 coecosite
  
  INNER JOIN ecologicalsite ON ecologicalsite.ecositeiid = coecosite.ecositeiidref
  
  ORDER BY coiid;"
  
  # setup connection local NASIS
  channel <- RODBC::odbcDriverConnect(connection = getOption("soilDB.NASIS.credentials"))
  
  # exec query
  d <- RODBC::sqlQuery(channel, q, stringsAsFactors=FALSE)
  
  # check for more than 1 record / coiid
  idx <- which(table(d$coiid) > 1)
  if(length(idx) > 0) {
    dupes <- names(idx)
    assign('multiple.ecosite.per.coiid', value=dupes, envir=soilDB.env)
    message("-> QC: multiple ecosites / component. Use `get('multiple.ecosite.per.coiid', envir=soilDB.env)` for related coiid values.")
  }
    
  # close connection
  RODBC::odbcClose(channel)
  
  # recode metadata domains
  #this is a soilDB internal function...
  #d <- .metadata_replace(d)
  
  # done
  return(d)
}

get_component_eplant_data_from_NASIS_db <- function() {
  # must have RODBC installed
  if(!requireNamespace('RODBC'))
    stop('please install the `RODBC` package', call.=FALSE)
  
  q <- "SELECT coiidref as coiidref, coeplantsiid, lplantiidref, forestunprod, rangeprod, coeplants.recwlupdated, coeplants.recuseriidref FROM coeplants;"
  
  # setup connection local NASIS
  channel <- RODBC::odbcDriverConnect(connection = getOption("soilDB.NASIS.credentials"))
  
  # exec query
  d <- RODBC::sqlQuery(channel, q, stringsAsFactors=FALSE)
  
  # close connection
  RODBC::odbcClose(channel)
  
  # recode metadata domains
  #this is a soilDB internal function...
  #d <- .metadata_replace(d)
  
  # done
  return(d)
}

get_NASIS_user_data <- function() {
  # must have RODBC installed
  if(!requireNamespace('RODBC'))
    stop('please install the `RODBC` package', call.=FALSE)
  q <- "SELECT useriid as useriid, username, useraffiliation, useremailaddr FROM nasisuser;"
  # setup connection local NASIS
  channel <- RODBC::odbcDriverConnect(connection = getOption("soilDB.NASIS.credentials"))
  d <- RODBC::sqlQuery(channel, q, stringsAsFactors=FALSE)
  RODBC::odbcClose(channel)
  return(d)
}


get_component_fprod_data_from_NASIS_db <- function() {
  # must have RODBC installed
  if(!requireNamespace('RODBC'))
    stop('please install the `RODBC` package', call.=FALSE)
  
  q <- "SELECT coiidref as coiidref, lplantiidref, siteindexbase, siteindex, siteindexstddev, fprodcmai, fprodage, coforprod.recwlupdated, coforprod.recuseriidref FROM coforprod;"
  
  # setup connection local NASIS
  channel <- RODBC::odbcDriverConnect(connection = getOption("soilDB.NASIS.credentials"))
  
  # exec query
  d <- RODBC::sqlQuery(channel, q, stringsAsFactors=FALSE)
  
  # close connection
  RODBC::odbcClose(channel)
  
  # recode metadata domains
  #this is a soilDB internal function...
  #d <- .metadata_replace(d)
  
  # done
  return(d)
}

get_legend_from_NASIS_db <- function() {
  if(!requireNamespace('RODBC'))
    stop('please install the `RODBC` package', call.=FALSE)
  q <- "SELECT nationalmusym, dmuiid, musym, muname, mustatus FROM legend AS l
          INNER JOIN lmapunit AS lmu ON lmu.liidref = l.liid
          INNER JOIN mapunit AS mu ON mu.muiid = lmu.muiidref
          INNER JOIN correlation AS cor ON cor.muiidref = mu.muiid
          INNER JOIN datamapunit AS dmu ON dmu.dmuiid = cor.dmuiidref
        WHERE cor.repdmu = 1 AND lmu.mustatus != 4"
  #does not join to component           INNER JOIN component AS co ON co.dmuiidref = dmu.dmuiid 
  channel <- RODBC::odbcDriverConnect(connection = getOption("soilDB.NASIS.credentials"))
  d <- RODBC::sqlQuery(channel, q, stringsAsFactors=FALSE)
  RODBC::odbcClose(channel)
  return(d)
}

c <-  as.data.frame(site(fetchNASIS_components(SS = TRUE)))
l <- get_legend_from_NASIS_db()
c <- join(c, l, by="dmuiid")

#uses modified version of soilDB function
e <-  as.data.frame(get_component_esd_data_from_NASIS_db2())

#new soilDB type functions
ep <- as.data.frame(get_component_eplant_data_from_NASIS_db())
fp <- as.data.frame(get_component_fprod_data_from_NASIS_db())

users <- as.data.frame(get_NASIS_user_data())

names(ep) <- paste0("ep_",names(ep))
names(fp) <- paste0("fp_",names(fp))

c <- c[grepl(c$dmudesc,pattern=dmupattern),] #narrow components based on user supplied pattern

ce <- join(c,e,by="coiid")

#just checks to see if there is at least one existing plants record correspondign to the component id
ce$plants <- ce$coiid %in% ep$ep_coiidref 

#just checks to see if there is at least one forest prod record correspondign to the component id
ce$forestp <- ce$coiid %in% fp$fp_coiidref 

#make a more useful name field
users$recuseriidref <- users$useriid
ce$user_name <- join(ce,users,by="recuseriidref")$username

#simplify drainage class to improve printing appearance; 
#       could relevel factors explicitly but that would be dependent on all classes occuring in the original dataset.
ce$drainage <- sub(pattern="drained",replacement="",x=as.character(ce$drainagecl))
ce$drainage <- sub(pattern="[Ss]omewhat",replacement="S",x=as.character(ce$drainage))
ce$drainage <- sub(pattern="[Ww]ell",replacement="W",x=as.character(ce$drainage))
ce$drainage <- sub(pattern="[Mm]oderately",replacement="M",x=as.character(ce$drainage))
ce$drainage <- sub(pattern="[Ee]xcessively",replacement="E",x=as.character(ce$drainage))
ce$drainage <- sub(pattern="[Pp]oorly",replacement="P",x=as.character(ce$drainage))
ce$drainage <- sub(pattern=" ",replacement="",x=as.character(ce$drainage))
#ce$drainage <- ce$drainagecl

#choose a few informative attributes to display
namez <- c("musym","dmudesc","coiid","compname","comppct_r","ecositeid","taxsubgrp","taxpartsize","drainage","plants","forestp","recwlupdated","user_name")

#order by musym (alphabetic/numeric order) and by component percentage (largest first)
ce <- ce[order(ce$musym, -ce$comppct_r), namez]
```

```{r, echo=F, results="asis"}
for(ss in 1:length(unique(ce$dmudesc))) {
  ce.sub <- ce[which(ce$dmudesc == unique(ce$dmudesc)[ss]), ]
  cat("####", ce.sub$musym[1]," : ", ce.sub$dmudesc[1], "\n")
  print(kable(unique(ce.sub[, -2]), row.names = F, align='c'))
  cat("\n***\n")
}
```